### PR TITLE
Type safety for arrays

### PR DESCRIPTION
**Pull request by calebwilson706**
Typed items inside arrays are something we really wanted to use in our project, this PR shows how i would implement it, feedback would be appreciated.

### CODE REVIEW

**Comment by calebwilson706** [comment]
issue here -> 
#343

**Comment by calebwilson706** [comment]
Can update the documentation also, didn't want to spend any time on it until this gets some 👀

**Comment by mobsense** [comment]
Sorry for the delay, but I'm ready to dig into this now.

The changes look pretty good and surgical.

I was wondering would an alternate schema syntax be possible without `items`. i.e. apply the nested `schema` to array elements if the type == Array. E.g.

```
        User: {
            pk:          { type: String, value: '${_type}#${id}' },
            sk:          { type: String, value: '${_type}#' },
            id:          { type: String, generate: 'ulid' },
            accountId:   { type: String },
            name:        { type: String },
            email:       { type: String },

            preferences:    { type: Array, schema: {
                key: { type: String },
                value:    { type: String },
            }}
        }
```

This would be a little simpler and cleaner but perhaps less explicit than your proposed:

```
            preferences:    { type: Array, items: {
                type: Object, schema: {
                    key: { type: String },
                    value:    { type: String },
                }
            }}
```

Please feel free to argue either way.

Michael

**Comment by calebwilson706** [comment]
Yeah I'm happy to go with using the schema attribute, just wondering how this would look like for a list of primitives then? Can we define the schema to be a number just?

**Comment by mobsense** [comment]
Ah, you are right. Your way is necessary.

**Comment by mobsense** [comment]
Thank you. This is a great patch. Do you want to update the docs too?

**Comment by calebwilson706** [comment]
@mobsense yeah i'm happy to update the docs, however i have a pretty full schedule for today and tomorrow so will most likely be the end of the week if thats ok?

**Comment by mobsense** [comment]
Cool. That would be great.

**Comment by calebwilson706** [comment]
@mobsense hello, where all do i have to update the docs, is it just the README.md file or is there other places that need chanegd?

**Comment by tombailey14** [comment]
@mobsense Hi, just wondering if this can be released? Would be very useful to have typed arrays on work I am doing atm. Thanks

**Comment by mobsense** [comment]
@calebwilson706 Docs are here: https://github.com/sensedeep/onedoc

**Comment by mobsense** [comment]
We're just doing some tests and pulling a few issues when using this on some of our live production sites. 

Should be soon though over the next 4 days.

**Pull request merged**
