### PR TITLE
typescriptify

### PR DESCRIPTION
**Pull request by hffmnn**
I don't know if this is of interest, but I started to write some classes in TS, which should give better types in the `d.ts` files.

### CODE REVIEW

**Comment by mobsense** [comment]
Hi, Thanks for your effort on this.

Can you please explain what this does. It is hard to accept a pull request that does a complete change of several files. Much better to have a detailed explanation of each change and/or a more surgical pull request with diffs that we can analyze.

**Comment by hffmnn** [comment]
Hi,

I guess that's the problem when moving from one filetype to another: git does not see this as a move, so it's a remove and a add, so there's no diff comparison for it.

In `Dynamo.ts` the main changes are:
* Added Types for the params
* Added input and return types for the methods
* The public instance variables are clear to see before the constructor
* Remove the `send` and used `this.client.send` directly because I could not come up with clever types for `send`.

In `ULID.ts` the main changes are:
* Added input and return types for the methods, still some `any` (sorry)
* Tried to figure out via the unit tests what allowed types for the `when` parameter are

The only idea I can come up with, is to use githubs markdown diff feature:

`git diff main:src/Dynamo.js src/Dynamo.ts`

```diff
diff --git a/src/Dynamo.js b/src/Dynamo.ts
index 856fe59..24d2e89 100644
--- a/src/Dynamo.js
+++ b/src/Dynamo.ts
@@ -1,8 +1,7 @@
 /*
-    Dynamo.js -- AWS V3 SDK API
+    Dynamo.ts -- AWS V3 SDK API
 
     This module provides a wrapper and convenience API over the AWS V3 SDK.
-    It is used by OneTable internally and is not a public API.
 
     Use:
         import {Model, Table} from 'dynamodb-onetable'
@@ -14,26 +13,82 @@
     */
 
 import {
+    AttributeValue,
     BatchGetItemCommand,
+    BatchGetItemCommandInput,
     BatchWriteItemCommand,
+    BatchWriteItemCommandInput,
     CreateTableCommand,
+    CreateTableCommandInput,
     DeleteItemCommand,
+    DeleteItemCommandInput,
     DeleteTableCommand,
+    DeleteTableCommandInput,
     DescribeTableCommand,
+    DescribeTableCommandInput,
+    DynamoDBClient,
     GetItemCommand,
+    GetItemCommandInput,
     ListTablesCommand,
+    ListTablesCommandInput,
     PutItemCommand,
+    PutItemCommandInput,
     QueryCommand,
+    QueryCommandInput,
     ScanCommand,
+    ScanCommandInput,
     TransactGetItemsCommand,
+    TransactGetItemsCommandInput,
     TransactWriteItemsCommand,
+    TransactWriteItemsCommandInput,
     UpdateItemCommand,
+    UpdateItemCommandInput
 } from '@aws-sdk/client-dynamodb'
-
-import {marshall, unmarshall} from '@aws-sdk/util-dynamodb'
+import {
+    marshall,
+    marshallOptions,
+    unmarshall,
+    unmarshallOptions
+} from '@aws-sdk/util-dynamodb'
+
+interface DynamoParams {
+    client?: DynamoDBClient
+    marshall?: <T extends { [K in keyof T]: any }>(
+        data: T,
+        options?: marshallOptions | undefined
+    ) => {
+        [key: string]: AttributeValue
+    }
+    unmarshall?: (
+        data: {
+            [key: string]: AttributeValue
+        },
+        options?: unmarshallOptions | undefined
+    ) => {
+        [key: string]: any
+    }
+}
 
 export class Dynamo {
-    constructor(params = {}) {
+    client: DynamoDBClient
+    params: any
+    V3: boolean
+    marshall: <T extends { [K in keyof T]: any }>(
+        data: T,
+        options?: marshallOptions | undefined
+    ) => {
+        [key: string]: AttributeValue
+    }
+    unmarshall: (
+        data: {
+            [key: string]: AttributeValue
+        },
+        options?: unmarshallOptions | undefined
+    ) => {
+        [key: string]: any
+    }
+
+    constructor(params: DynamoParams = {}) {
         this.client = params.client
         this.params = params
         this.marshall = marshall
@@ -41,78 +96,74 @@ export class Dynamo {
         this.V3 = true
     }
 
-    async createTable(params) {
+    async createTable(params: CreateTableCommandInput) {
         let command = new CreateTableCommand(params)
-        return await this.send(command)
+        return await this.client.send(command)
     }
 
-    async deleteTable(params) {
+    async deleteTable(params: DeleteTableCommandInput) {
         let command = new DeleteTableCommand(params)
-        return await this.send(command)
+        return await this.client.send(command)
     }
 
-    async delete(params) {
+    async delete(params: DeleteItemCommandInput) {
         let command = new DeleteItemCommand(params)
-        return await this.send(command)
+        return await this.client.send(command)
     }
 
-    async describeTable(params) {
+    async describeTable(params: DescribeTableCommandInput) {
         let command = new DescribeTableCommand(params)
-        return await this.send(command)
+        return await this.client.send(command)
     }
 
-    async get(params) {
+    async get(params: GetItemCommandInput) {
         let command = new GetItemCommand(params)
-        return await this.send(command)
+        return await this.client.send(command)
     }
 
-    async find(params) {
+    async find(params: QueryCommandInput) {
         let command = new QueryCommand(params)
-        return await this.send(command)
+        return await this.client.send(command)
     }
 
-    async listTables(params) {
+    async listTables(params: ListTablesCommandInput) {
         let command = new ListTablesCommand(params)
-        return await this.send(command)
+        return await this.client.send(command)
     }
 
-    async put(params) {
+    async put(params: PutItemCommandInput) {
         let command = new PutItemCommand(params)
-        return await this.send(command)
+        return await this.client.send(command)
     }
 
-    async scan(params) {
+    async scan(params: ScanCommandInput) {
         let command = new ScanCommand(params)
-        return await this.send(command)
+        return await this.client.send(command)
     }
 
-    async update(params) {
+    async update(params: UpdateItemCommandInput) {
         let command = new UpdateItemCommand(params)
-        return await this.send(command)
+        return await this.client.send(command)
     }
 
-    async batchGet(params) {
+    async batchGet(params: BatchGetItemCommandInput) {
         let command = new BatchGetItemCommand(params)
-        return await this.send(command)
+        return await this.client.send(command)
     }
 
-    async batchWrite(params) {
+    async batchWrite(params: BatchWriteItemCommandInput) {
         let command = new BatchWriteItemCommand(params)
-        return await this.send(command)
+        return await this.client.send(command)
     }
 
-    async transactGet(params) {
+    async transactGet(params: TransactGetItemsCommandInput) {
         let command = new TransactGetItemsCommand(params)
-        return await this.send(command)
+        return await this.client.send(command)
     }
 
-    async transactWrite(params) {
+    async transactWrite(params: TransactWriteItemsCommandInput) {
         let command = new TransactWriteItemsCommand(params)
-        return await this.send(command)
-    }
-
-    async send(cmd) {
-        return await this.client.send(cmd)
+        return await this.client.send(command)
     }
 }
 ```

`git diff main:src/ULID.js src/ULID.ts`

```diff
diff --git a/src/ULID.js b/src/ULID.ts
index 408e5a6..c237ade 100644
--- a/src/ULID.js
+++ b/src/ULID.ts
@@ -1,5 +1,5 @@
 /*
-    ULID.js -- Universal Unique Lexicographically Sortable Identifier
+    ULID.ts -- Universal Unique Lexicographically Sortable Identifier
     https://github.com/ulid/spec
  */
 import Crypto from 'crypto'
@@ -11,20 +11,25 @@ const RandomLength = 16
 const TimeLen = 10
 
 export default class ULID {
-    constructor(when) {
-        this.when = isNaN(when) ? when = new Date() : new Date(when)
+    when: Date
+    constructor(when?: Date | undefined) {
+        if (when === undefined) {
+            this.when = new Date()
+        } else {
+            this.when = when
+        }
     }
 
-    toString() {
+    toString(): string {
         return this.getTime(this.when) + this.getRandom()
     }
 
-    decode(ulid) {
-        ulid = ulid.toString()
-        if (ulid.length !== (TimeLen + RandomLength)) {
+    decode(ulid: any) {
+        const ulidStr: string = ulid.toString()
+        if (ulidStr.length !== TimeLen + RandomLength) {
             throw new Error('Invalid ULID')
         }
-        let letters = ulid.substr(0, TimeLen).split('').reverse()
+        let letters = ulidStr.substr(0, TimeLen).split('').reverse()
         return letters.reduce((accum, c, index) => {
             let i = Letters.indexOf(c)
             if (i < 0) {
@@ -35,17 +40,17 @@ export default class ULID {
         }, 0)
     }
 
-    getRandom() {
+    getRandom(): string {
         let bytes = []
         let buffer = Crypto.randomBytes(RandomLength)
         for (let i = 0; i < RandomLength; i++) {
             //  Letters is one longer than LettersLen
-            bytes[i] = Letters[Math.floor(buffer.readUInt8(i) / 0xFF * LettersLen)]
+            bytes[i] = Letters[Math.floor((buffer.readUInt8(i) / 0xff) * LettersLen)]
         }
         return bytes.join('')
     }
 
-    getTime(now) {
+    getTime(now: any): string {
         let bytes = []
         for (let i = 0; i < TimeLen; i++) {
             let mod = now % LettersLen

```

**Comment by mobsense** [comment]
Hi Christian,  Thanks for the extra details that helps.

I'd love to have better .d.ts files, but don't really want to switch to TS files, especially not for just a couple of files. If we did switch, we'd do all the source.

Would it be possible to make improvements from your prototyping ts files to the original .d.ts files? Especially the Dynamod.d.ts is pretty bare (which I guess is what prompted your efforts).

Other comments:

* Don't want to import everything in Dynamo from '@aws-sdk/client-dynamodb. We only want to import the commands we actually use. That helps tree shaking for minimal footprint.

**Comment by hffmnn** [comment]
Hi,

> I'd love to have better .d.ts files, but don't really want to switch to TS files, especially not for just a couple of files. If we did switch, we'd do all the source.

From my perspective/experience I would always do it step by step and not in one big rewrite. Especially because `tsc` supports that mixed JS/TS mode.

> Would it be possible to make improvements from your prototyping ts files to the original .d.ts files? Especially the Dynamod.d.ts is pretty bare (which I guess is what prompted your efforts).

Sure, feel free to pick whatever makes the existing typings better.

> Don't want to import everything in Dynamo from '@aws-sdk/client-dynamodb. We only want to import the commands we actually use. That helps tree shaking for minimal footprint.

Not sure if I understand you 100%. The generated code in mjs only imports what's needed (the commands), the cjs imports everything (as before).

**Comment by mobsense** [comment]
Agree on step, by step changing. But we've not yet decided to take those steps.

I'd love to manually apply your changes to Dynamo, Ulid etc and strengthen our typings.

If we do switch to TS, will dig up this pull request and it will save time.

Some shakers do a better job than others. Doing an import in Dynamo of the full API may not get removed. E.g. AttributeValue which we don't use.  Not a big deal given the direction we're taking.

Lastly, thank you very much for your effort on this. We will update the .d.ts over the weekend and hopefully that will help your use-cases. Please feel free to suggest and propose pull requests for any other features or issue you identify.

**Comment by hffmnn** [comment]
> Lastly, thank you very much for your effort on this. We will update the .d.ts over the weekend and hopefully that will help your use-cases. Please feel free to suggest and propose pull requests for any other features or issue you identify.

Thanks, will do. And thank you for the library.

**Comment by mobsense** [comment]
I've cherry picked some fixes for ULID.d.ts and Dynamo.d.ts -- but pretty minimal.

Please feel free to suggest surgical changes to any *.d.ts file where we can improve our typescript definitions.

My goal is to keep it simple, readable and yet offer good TS support.

**Pull request closed without merging**
