### PR TITLE
params.fields are not respected when using table.getItem() or table.queryItems()

### PR DESCRIPTION
**Pull request by ThijsJung**
More details can be found in the issue I filed (#497). I gave it a go and tried to scratch my own itch, let me know what you think. Please feel free to tell me if I forgot anything or if you think there's a better way to fix this issue. Thanks!

### CODE REVIEW

**Comment by mobsense** [comment]
Thank you for contributing this. Looks pretty good. I'll give it a deeper look over the next few days.

One thing: keep debug.ts unchanged as it is the file for users to modify and submit issues.  Create a new TS file if you need.

Thank you!

**Comment by ThijsJung** [comment]
Thanks for your fast reply! Sure, take your time, and let me know if you see anything that you'd like to see changed. Now that I think about it, I'm not 100% certain to updated all the test that are applicable, so if you know of another method that accepts `fields` that I missed, let me know.

I'll take a moment to revert `debug.ts` and will put mine in a gist instead.

Thanks!

**Comment by ThijsJung** [comment]
By the way, while working on this I ran into a couple of things that are not broken but that might clean things up a bit (1) or make development (IMO) a bit more convenient (2). Let me know if you're interested in a P.R. for these (kinds of) items, I'd be happy to contribute.

Cheers!

1. When [instantiating a genericModel](https://github.com/sensedeep/dynamodb-onetable/blob/3fb91b089efaf4b07aeb1e30c5bb338ad5d30314/src/Schema.js#L151) we pass it both the name (`_Generic`) and an option called (`generic: true`). This can be simplified, I don't think we need the option.
2. While developing I didn't manage to run a test separately (in for instance, in [the `crud` tests](https://github.com/sensedeep/dynamodb-onetable/blob/3fb91b089efaf4b07aeb1e30c5bb338ad5d30314/test/crud.ts). This seems to be because the `user` is created in a separate test which means that that test has to always be run. I also found that if do limit the amount of fields returned, some of my later tests would break because they expected the fields to be present on the user.

**Comment by ThijsJung** [comment]
Perfect, thanks for the update. I'll keep an eye out for the new release. I was happy to help out, keep up the great work!

**Pull request closed without merging**
