### PR TITLE
fix: Update and remove unique property

### PR DESCRIPTION
**Pull request by kujtimiihoxha**
This is a followup to https://github.com/sensedeep/dynamodb-onetable/pull/169 I did not notice that I had to change multiple places.

### CODE REVIEW

**Comment by mobsense** [comment]
Thank you.

**Comment by trustthe27** [comment]
Hi @kujtimiihoxha, thanks for fixing. I had this problem with the 2.1.0 release and it's gone for the current `main` version.

But it seems, there is still a bug left. Because after a delete, the `_unique` item is not removed from the database. So adding another item with the same unique key afterwards will fail.

 That behaviour also doesn't match with the documentation:
 "...
 The created item and the unique item will be created in a transparent transaction so that the item will be created only if all the unique fields are truly unique. The `remove` API will similarly remove the special unique item.
 ..."

**Comment by trustthe27** [comment]
After checking the sourcecode, I know where my problem is rooted.

I tried something like this:

```javascript
  this.UserDbModel.remove(
    { id },
    { transaction },
  );
```

What I needed was something like this, to get the `_unique` item for the field `email` removed as well:

```javascript
this.UserDbModel.remove(
  { id, email },
  { transaction },
);
```

Otherwise the generated PK to delete the `_unique` item is `_unique#User#email#undefined`, what will obviously not work.

For me this works now, but it's an easy trap to fall in 😉

**Comment by mobsense** [comment]
I'll see if we can add a check for unresolved value templates for remove. Should get a warning or exception I think if the keys are not fully specified.

**Comment by trustthe27** [comment]
While experiencing this problem, I would have preferred an exception that kept the data intact, by rolling back the transaction.
Could be done as a check on missing keys, or a DynamoDB condition expression to check if the unique key does exist before removing it.

**Comment by mobsense** [comment]
Just committed a fix. Will throw an exception. Transaction will not complete.

**Pull request merged**
